theme: jekyll-theme-slate
title: Competitions
description: Competitions is an open source tool to run NIH-style peer review of competitions, pilot projects, and research proposals in a cloud-based consortium-wide single sign-on platform.
github:
  owner_url: "https://github.com/NUARIG"
  owner_name: Northwestern University Applied Research Informatics Group
